payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    path('', views.CartView, name='cart'),
    path('orderplaced/', views.order_placed, name='order_placed'),
    # path('error/', views.Error.as_view(), name='error'),
    path('webhook/', views.stripe_webhook),    
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('about/', views.about_info, name='about_info'),
    path('<slug:slug>', views.product_info, name='product_info'),
    path('store/<slug:category_slug>/', views.categories_list, name='categories_list'),
    path('get-quantities/', views.get_quantities, name='get_quantities'),
]

store_cart/urls.py
from django.urls import path

from . import views

app_name = 'store_cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

templates/cart/cart_info.html
{% extends "base.html" %}
{% load static %}
{% block title %}Shopping Cart{% endblock %}
{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="pb-3 h2 text-center">Your shopping cart</div>
        {% if cart %}
        {% for item in cart %}
        {% with product=item.product %}
        <div data-index="{{ product.id }}" class="row mb-4 border product-item">
            <div class="col-md-3 col-lg-2 order-md-first bg-light">
                {% for image in product.product_image.all %}
                {% if image.is_feature %}
                <a href="{{ product.get_abs_url }}">
                    <img class="img-fluid mx-auto d-block" width="auto" alt="Responsive image" src="{{ image.image.url }}">
                </a>
                {% endif %}
                {% endfor %}
            </div>
            <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                <a href="{{ product.get_abs_url }}" class="text-decoration-none text-reset">
                    <h1 class="h5 pt-2">{{ product.title }}</h1>
                </a>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">{{ product.condition }}</div>
                            <div class="col-6 text-end"><span class="h6 fw-bold">${{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-12">
                                <label for="select">Qty</label>
                                <select id="select{{product.id}}">
                                    <option value="" selected disabled hidden> {{ item.quantity }} </option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>
                                <button type="button" id="update-button" data-index="{{product.id}}"
                                    class="btn btn-outline-secondary btn-sm update-button">
                                    Update
                                </button>
                                <button type="button" id="delete-button" data-index="{{product.id}}"
                                    class="btn btn-outline-secondary btn-sm delete-button">
                                    Delete
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}
        <div class="col-12 text-end">
            <div class="h5 fw-bold">Total: $
                <div id="subtotal" class="d-inline-flex">
                    {{ cart.get_total_cart_price }}
                </div>
            </div>
        </div>
        <div class="col text-center">
            <a role="button" href="{% url "payment:cart" %}" class="w-50 btn btn-success fw-bold"
                type="button">Checkout</a>
        </div>
        {% else %}
        <h2 class="h5 text-center pt-5">Your cart is empty.</h2>
        {% endif %}
    </div>
</div>

<script>
    // Delete item from cart
    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "store_cart:cart_delete" %}',
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                $('.product-item[data-index="' + prodid + '"]').remove();
                document.getElementById("cart-qty").innerHTML = json.quantity
                document.getElementById("subtotal").innerHTML = json.subtotal
            },
            error: function (xhr, errmsg, err) {}
        });
    })

    // Update item in cart
    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "store_cart:cart_update" %}',
            data: {
                productid: $(this).data('index'),
                productqty: $('#select' + prodid + ' option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("cart-qty").innerHTML = json.quantity
                document.getElementById("subtotal").innerHTML = json.subtotal
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>
{% endblock %}