account/urls.py
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.urls import path

from .forms import UserLoginForm
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    # Email activation
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/edit/', views.change_details, name='change_details'),
    path('dashboard/delete/', views.account_delete, name='account_delete'),
    path('dashboard/delete_profile/', TemplateView.as_view(template_name='account/user/delete_profile.html'), name='delete_profile')
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('about/', views.about_info, name='about_info'),
    path('<slug:slug>', views.product_info, name='product_info'),
    path('store/<slug:category_slug>/', views.categories_list, name='categories_list'),
    path('get-quantities/', views.get_quantities, name='get_quantities'),
]

store_cart/urls.py
from django.urls import path

from . import views

app_name = 'store_cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

templates/base.html
<!doctype html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title %}Kicksale{%endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
            <div class="container-fluid">
                <a href="/" class="navbar-brand">
                    <img src="{% static "media/logo.png" %}" width="150px">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle px-2" data-bs-toggle="dropdown" href="#"
                                id="navbarDropdown" role="button" aria-expanded="false">
                                Shop
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:products_all" %}">
                                        All
                                    </a>
                                </li>
                                <hr class="mt-0 mb-0"/>
                                {% for c in categories %}
                                <li {% if c.slug == category.slug %} class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_abs_url }}">{{ c.name|title }}</a>
                                    {% for cat in c.get_children %}
                                        <a class="dropdown-item" href="{{ cat.get_abs_url }}"> - {{ cat.name|title }}</a>
                                    {% endfor %}
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="{% url "store:about_info" %}" class="nav-link px-2">About</a>
                        </li>
                    </ul>
                    <a type="button" role="button" href="{% url "store_cart:cart_summary" %}"
                        class="btn btn-outline-light border-0">

                        {% with total_qty=cart|length %}
                            <div id="cart-qty" class="d-inline-flex">
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% endif %}
                            </div>
                        {% endwith %}

                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        <span class="fs15 fw500">Cart</span>
                    </a>

                    {% if user.is_authenticated %}
                    <a type="button" role="button" href="{% url "account:dashboard" %}"
                        class="btn btn-outline-light border-0 basket-btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                            class="bi bi-person" viewBox="0 0 16 16">
                            <path
                                d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                        </svg>
                        <span class="fs15 fw500">My Account</span>
                    </a>

                    <a type="button" role="button" href="{% url "account:logout" %}"
                        class="btn btn-outline-light border-0 basket-btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                            class="bi bi-door-closed" viewBox="0 0 16 16">
                            <path
                                d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                            <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                        </svg>
                        <span class="fs15 fw500">Logout</span>
                    </a>
                    {% else %}
                    <a type="button" role="button" href="{% url "account:login" %}"
                        class="btn btn-outline-light border-0 basket-btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                            class="bi bi-door-closed" viewBox="0 0 16 16">
                            <path
                                d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                            <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                        </svg>
                        <span class="fs15 fw500">Login</span>
                    </a>
                    {% endif %}
                    
                </div>
            </div>
        </nav>
    </header>

    <div id="content">{% block content %}{% endblock %}</div>

    <footer class="container py-5">
        <div class="row">
            <div class="col-6 col-md">
            </div>
            <div class="col-6 col-md">
            </div>
            <div class="col-6 col-md">
            </div>
            <div class="col-6 col-md">
            </div>
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; 2022 Elgiz Abbasov</small>
                <ul class="list-unstyled text-small">
                    <li style="display: inline">
                        <a style="text-decoration: none" href="https://github.com/elgizabbasov">
                            <img src="{% static "media/GitHub.png" %}" width="40px">
                        </a>
                    </li>
                    <li style="display: inline">
                        <a style="text-decoration: none" href="https://www.linkedin.com/in/elgizabbasov/">
                            <img src="{% static "media/LinkedIn.png" %}" width="40px">
                        </a>
                    </li>
                    <li style="display: inline">
                        <a style="text-decoration: none" href="mailto:elgizabbasov2001@gmail.com">
                            <img src="{% static "media/Email.png" %}" width="40px">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
</body>

</html>