store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('about/', views.about_info, name='about_info'),
    path('<slug:slug>', views.product_info, name='product_info'),
    path('store/<slug:category_slug>/', views.categories_list, name='categories_list'),
    path('get-quantities/', views.get_quantities, name='get_quantities'),
]

store_cart/urls.py
from django.urls import path

from . import views

app_name = 'store_cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

store/models.py
""" Kicksale store models    
"""
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator
from decimal import Decimal

from mptt.models import MPTTModel, TreeForeignKey


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(in_stock=True)


class Category(MPTTModel):
    """Category implemented using MPTT
    """
    name = models.CharField(verbose_name=_("Category Name"), 
                            help_text=_("Required and unique"),
                            max_length=255, 
                            unique=True,
                            db_index=True)
    slug = models.SlugField(verbose_name=_("Category URL"),
                            max_length=255, 
                            unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]
    
    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        
    def __str__(self):
        return self.name
    
    def get_abs_url(self):
        return reverse('store:categories_list', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.RESTRICT)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='product_created_by', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    brand = models.CharField(max_length=255)
    condition = models.CharField(max_length=255)
    ## TODO: Multiple images - Only one image per product possible currently
    price = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        validators=[MinValueValidator(Decimal('0.01'))]
    )
    slug = models.SlugField(max_length=255)
    in_stock = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)
    
    def __str__(self):
        return self.title
    
    def get_abs_url(self):
        return reverse('store:product_info', args=[self.slug])


class Size(models.Model):
    product = models.ForeignKey(Product, related_name='sizes', on_delete=models.RESTRICT)
    in_stock = models.BooleanField(default=True)
    prod_size = models.DecimalField(max_digits=3, decimal_places=1)
    created = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)

    def __str__(self) -> str:
        return str(self.prod_size)
        
    class Meta:
        verbose_name_plural = 'Sizes'
        ordering = ('-created',)
        # TODO: #4
        unique_together = ( 
                           ("product", "prod_size"),
        )

class ProductImage(models.Model):
    """Product images table
    """
    
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_image')
    image = models.ImageField(
        verbose_name=_("Image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    is_feature = models.BooleanField(default=False)

store/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from .models import Category, Size, Product


def categories_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category__in=Category.objects.get(slug=category_slug).get_descendants(include_self=True))
    return render(request, 'store/category.html', {'category': category, 'products': products})

def products_all(request):
    products = Product.objects.prefetch_related("product_image").filter(in_stock=True)
    return render(request, 'store/home.html', {'products': products})

def product_info(request, slug):
    product = get_object_or_404(Product, 
                                slug=slug, 
                                in_stock=True
    )
    sizes = Size.objects.filter(
             product=product, in_stock=True
    )
        
    return render(request, 'store/product_info.html', {'product': product, 'sizes': sizes})

def get_quantities(request):
    size = request.GET.get('size')
    quantities = list(Size.objects.filter(prod_size=size).values("quantity"))
    response_data = {
        "quantities": quantities
    }
    return JsonResponse(response_data)

def about_info(request):
    return render(request, 'store/about_info.html')

templates/store/about_info.html
{% extends "base.html" %}
{% block title %}About Kicksale{% endblock %}
{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="pb-3 h2">About</div>
        <p class="lead text-muted">This website was created to catalog current sneakers that I have for sale as well as for demo purposes of a fully functioning deployed e-commerce web application.
            Kicksale's front-end was built using Bootstrap 4 with Python 3.9.6 and Django 4.0.6 as the backend.</p>
    </div>
</div>

{% endblock %}

templates/store/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{category.name}}{% endblock %}
{% block content %}

<main>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h2">{{category.name|title}}</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% if not products %}
                <div class="col-12 text-center">There are currently no available products.</div>
                {% else %}
                {% for product in products %}

                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <a href="{{ product.get_abs_url }}">
                                {% for image in product.product_image.all %}
                                {% if image.is_feature %}
                                <a href="{{ product.get_abs_url }}">
                                    <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}">
                                </a>
                                {% endif %}
                                {% endfor %}
                            </a>
                            <p class="card-text">
                                <a class="text-dark text-decoration-none"
                                    href="{{ product.get_abs_url }}">{{ product.title }}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">${{product.price}}</small>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}
                {% endif %}

            </div>
        </div>
    </div>

</main>

{% endblock %}

templates/store/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Kicksale{% endblock %}
{% block content %}


<section class="py-5 text-center container">
    <div class="row py-lg-2">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Welcome to Kicksale</h1>
        </div>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="pb-2 h2">Trending</div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% if not products %}
                <div class="col-12 text-center">There are currently no available products.</div>
            {% else %}
            {% for product in products %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">

                        {% for image in product.product_image.all %}
                        {% if image.is_feature %}
                        <a href="{{ product.get_abs_url }}">
                            <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}">
                        </a>
                        {% endif %}
                        {% endfor %}

                        <p class="card-text">
                            <a class="text-dark text-decoration-none"
                                href="{{ product.get_abs_url }}">{{ product.title }}</a>
                        </p>

                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted">${{product.price}}</small>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
            {% endif %}

        </div>
    </div>
</div>


{% endblock %}

templates/store/product_info.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ product.title }}{% endblock %}
{% block content %}

<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                {% for image in product.product_image.all %}
                {% if image.is_feature %}
                <img class="img-fluid mx-auto d-block" width="400px" alt="Responsive image"
                    src="{{ image.image.url }}">
                {% else %}
                <img class="img-fluid d-block-inline pt-3" width="200px" alt="Responsive image"
                    src="{{ image.image.url }}">
                {% endif %}
                {% endfor %}
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.brand }}</span></p>
                <p>{{ product.condition|slice:":355" }}</p>
                <div class="border">
                    <form name="sizeForm" id="id_sizeForm" action="" method="get">
                        <div class="col border-bottom">
                            <div class="row p-3">
                                <div class="col-6">
                                    <label for="select">Sizes</label>
                                    <select name="size" id="size" form="id_sizeForm">
                                        {% for s in sizes %}
                                        <option value="{{s}}">{{ s }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-6 text-end"><span class="h4 fw-bold">${{ product.price }}</span></div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row p-3">
                                <div class="col-6">
                                    <label for="select">Qty</label>
                                    <select name="qty" id="qty" form="id_sizeForm">
                                        
                                    </select>
                                </div>
                                <div class="col-6 text-end"><button type="button" id="add-button" value="{{product.id}}"
                                        class="btn btn-secondary btn-sm">Add to
                                        cart</button></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "store_cart:cart_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#qty option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("cart-qty").innerHTML = json.quantity
            },
            error: function (xhr, errmsg, err) {}
        });
    });
</script>

<script>
    document.getElementById("size").addEventListener("change", function() {
        document.getElementById("qty").innerHTML = "";
        $.ajax({
            type: 'GET',
            url: 'get-quantities/',
            data:{
                size: $("#size").val(),
            },
            dataType: 'json',
            success:function(response){
                var select = document.getElementById("qty")
                for(var i=1; i<response.quantities[0]["quantity"] + 1; i++)
                {
                    var option = document.createElement("option");
                    option.value = i;
                    option.innerHTML = i;
                    select.appendChild(option);
                }
            },
        });
    });
</script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById("qty").innerHTML = "";
        $.ajax({
            type: 'GET',
            url: 'get-quantities/',
            data:{
                size: $("#size").val(),
            },
            dataType: 'json',
            success:function(response){
                var select = document.getElementById("qty")
                for(var i=1; i<response.quantities[0]["quantity"] + 1; i++)
                {
                    var option = document.createElement("option");
                    option.value = i;
                    option.innerHTML = i;
                    select.appendChild(option);
                }
            },
        });
    }, false);
</script>
{% endblock %}